# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: LCM and HCF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  hcf_lcm:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: run the hcf and lcm app
      run: |
        python calculate_lcm_hcf.py > data/answers.txt
    - name: Upload the answers
      uses: actions/upload-artifact@v2.3.1
      with:
        name: answers
        path: data/*

      
